version: "3"
services:
  web:
    # replace username/repo:tag with your name and image details
    image: mytornadoappdeploy
    deploy:
      replicas: 10  # for creating replicas update here
      restart_policy:
        condition: on-failure
      resources:
        limits:
          cpus: "0.1"
          memory: 100M
    ports:
      - "8888:8888"
    networks:
      - webnet
  visualizer:
    image: dockersamples/visualizer:stable
    ports:
      - "8080:8080"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
    deploy:
      placement:
        constraints: [node.role == manager]
    networks:
      - webnet
  # mongodb:
  #   image: mongo:latest
  #   container_name: "mongodb"
  #   environment:
  #     - MONGO_DATA_DIR=/data/db
  #     - MONGO_LOG_DIR=/dev/null
  #   volumes:
  #     - ./data/db:/data/db
  #   ports:
  #     - "27017:27017"
  #   command: mongod --smallfiles --logpath=/dev/null # --quiet
networks:
  webnet:
